### ISSUE TITLE
Error creating pileup

### ISSUE THREAD

**Issue by yassineS** [BoyanZhou/AntCaller#2]
I am running into issues creating a pileup from my bam file:

```
% samtools view -h my.bam | python AntCaller-1.1.py --pileup -o out

Traceback (most recent call last):
  File "AntCaller-1.1.py", line 70, in <module>
    temp_list.reverse()
AttributeError: 'range' object has no attribute 'reverse'
```

Thank you,
Y

**Comment by ThibauldMichel** [comment]
Same error on my side, with a few additional afterward:

```
Traceback (most recent call last):
  File "AntCaller-1.1.py", line 70, in <module>
    temp_list.reverse()
AttributeError: 'range' object has no attribute 'reverse'
Traceback (most recent call last):
  File "AntCaller-1.1.py", line 226, in <module>
    damagetag = damageinfo(read, MD)
  File "AntCaller-1.1.py", line 140, in damageinfo
    ncount_other_three[readlen - pos_five - 1] += 1
IndexError: list index out of range
Traceback (most recent call last):
  File "AntCaller-1.1.py", line 243, in <module>
    fpileup = open(fpileupname, 'r')
```
Looking forward for your insights.

Thibauld
